#pragma config(Sensor, in1,    arm,            sensorPotentiometer)
#pragma config(Sensor, in2,    driveSelect,    sensorPotentiometer)
#pragma config(Sensor, in3,    pinchL,         sensorPotentiometer)
#pragma config(Sensor, in4,    pinchR,         sensorPotentiometer)
#pragma config(Sensor, dgtl1,  R1,             sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  L1,             sensorQuadEncoder)
#pragma config(Motor,  port1,           rDrive1,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           Lift1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LDrive1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rClaw,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rDrive2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Lift2,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LClaw,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LDrive2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Lift3,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          LDrive3,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"
#include "BackOver Functions.c"


//----------------------Motor Voids------------------------------//

void setDrivePower(int left, int right){   // Defining all of the motors for the drive
	motor[LDrive1] = left;
	motor[LDrive2] = left;
	motor[LDrive3] = left;
	motor[rDrive1] = right;
	motor[rDrive2] = right;

}

void setLiftPower(int power){   // Defining all of the motors for the lift
	motor[Lift1] = power;
	motor[Lift2] = power;
	motor[Lift3] = power;
}

// aton voids///////Tinin///////////////////////////////////////////////////////////////

void Liftaton(int targetVal, int liftspeed=127)         // void to
{
	int direction = sgn(targetVal - SensorValue[arm]);

	while (direction == sgn(targetVal - SensorValue[arm])) {
		setLiftPower(direction * liftspeed);
	}

	setLiftPower(0);
}


void driveaton(int targetVal, int leftDirection=1, int rightDirection=1, int power=100, int sampleTime=100)
{
	float gain = 0.0; //aggressiveness of correction

	int leftDist = 0;
	int rightDist = 0;
	int diff;

	leftDirection = sgn(leftDirection) * sgn(targetVal);
	rightDirection = sgn(rightDirection) * sgn(targetVal);
	targetVal = abs(targetVal);

	while(leftDist + rightDist < 2 * targetVal)
	{
		SensorValue[L1] = 0;
		SensorValue[R1] = 0;

		setDrivePower(leftDirection * power, rightDirection * (power + gain * diff));

		wait1Msec(sampleTime);

		diff += leftDist - rightDist;

		leftDist += abs(SensorValue[L1]);
		rightDist += abs(SensorValue[R1]);
	}

	setDrivePower(0, 0);
}

void Rightturn(int right, int power=100, int sampleTime=100)
{
	driveaton(right, 1, -1, power, sampleTime);
}

void Leftturn(int left, int power=100, int sampleTime=100)
{
	driveaton(left, -1, 1, power, sampleTime);
}

void pre_auton()
{

	bStopTasksBetweenModes = true;

}

void dumpty (){                 // Auto Dump with drive function

	Liftaton(3200);
	setLiftPower(-15);

	driveaton(-800);

	Liftaton(2260);

	pinchRRequestedValue = 1840;
	pinchLRequestedValue = 1805;

	Liftaton(1800);

	Liftaton(3500);

}

void dump (){                 // Auto Dump with no drive function

	Liftaton(3000);
	setLiftPower(15);

	pinchRRequestedValue = 1840;
	pinchLRequestedValue = 1805;

	Liftaton(1800);

	Liftaton(3500);

}







//TASKS!!!////TASKS!!!////TASKS!!!////TASKS!!!////TASKS!!!//

//-----------------SKILLS---------------------------//

task skils() {

	//Open claw for preset
	pinchRRequestedValue = 1840;
	pinchLRequestedValue = 1805;

	wait1Msec(1000);

	driveaton(-400);								//Pull Back to Ajust
	Liftaton(3000);

	Liftaton(3500);									//Lift back down to grab cube

	driveaton(400);				//-------------------------------------------  drive to get cube 1


	//Close claw to grab cube
	pinchRRequestedValue = 350;
	pinchLRequestedValue = 210;

	wait1Msec(800);       //wait for previous command to finish

	Liftaton(3000);

	driveaton(-800);   			//drive to fence

	Liftaton(2500);    		//lift cube over fence and throw

	//Start opening claw to get cube in far zone
	pinchRRequestedValue = 1290;
	pinchLRequestedValue = 1137;

	Liftaton(1800);    		//lift cube over fence and throw

	wait1Msec(300);       //wait for previous command to finish

	Liftaton(3500);				//lift back down to grab 2nd cube

	driveaton(1000);		//-------------------------------------------  drive to get cube 2

	// Grab seconed cube
	pinchRRequestedValue = 350;
	pinchLRequestedValue = 210;

	wait1Msec(800);       //wait for previous command to finish

	Liftaton(3000);

	driveaton(-1000); 	// Drive back to fence wtih cube

	Liftaton(1800);      // lift cube up toward fence and throw

	//release cube over fence
	pinchRRequestedValue = 1290;
	pinchLRequestedValue = 1137;

	Liftaton(3500);   	//lift back down to grab 3rd set of jacks

	driveaton(-100);

	driveaton(1000);		//-------------------------------------------  drive to get jacks

	pinchRRequestedValue = 350;
	pinchLRequestedValue = 210;

	wait1Msec(800);       //wait for previous command to finish

	driveaton(-400);

	dumpty();

	wait1Msec(300);       //wait for previous command to finish

	Liftaton(3000);

	driveaton(500);

	pinchRRequestedValue = 784;
	pinchLRequestedValue = 540;

	driveaton(150, 1, -1);

	Liftaton(3500);

	driveaton(500);

	pinchRRequestedValue = 350;
	pinchLRequestedValue = 210;

	wait1Msec(100);

	driveaton(-500);




}


//---------------------CENTER--------------------------//
task center() {

	driveaton(-220);

	pinchRRequestedValue = 1840;
	pinchLRequestedValue = 1805;

	wait1Msec(10);       //wait for previous command to finish
	driveaton(-180);


	wait1Msec(10);       //wait for previous command to finish
	driveaton(-550);

	Liftaton(1650);
	wait1Msec(100);       //wait for previous command to finish

	Liftaton(3600);

	driveaton(500);

	driveaton(450);

	pinchRRequestedValue = 350;
	pinchLRequestedValue = 210;
	wait1Msec(800);       //wait for previous command to finish

	driveaton(-150);

	pinchRRequestedValue = 1840;
	pinchLRequestedValue = 1805;

	driveaton(400);

	pinchRRequestedValue = 350;
	pinchLRequestedValue = 210;
	wait1Msec(800);       //wait for previous command to finish

	driveaton(-1200);

	Liftaton(3000);

	pinchRRequestedValue = 1840;
	pinchLRequestedValue = 1805;

	Liftaton(1600);

}

//-------------------------RIGHT--------------------------//
task RightAton() {

	driveaton(-200);

	pinchRRequestedValue = 1840;
	pinchLRequestedValue = 1805;

	wait1Msec(10);       //wait for previous command to finish
	driveaton(-150);

	driveaton(110, -1, 1);

	wait1Msec(10);       //wait for previous command to finish
	driveaton(-450);

	Liftaton(1700);

	driveaton(-150);

	wait1Msec(300);       //wait for previous command to finish
	Liftaton(3600); 																					//end of fence stuff

	pinchRRequestedValue = 1137;
	pinchLRequestedValue = 1137;         ///Open claw

	driveaton(350);

	driveaton(270, 1, -1);

	driveaton(1300);

	pinchRRequestedValue = 350;
	pinchLRequestedValue = 210;

	wait1Msec(300);       //wait for previous command to finish

	Liftaton(3000);

	driveaton(150, -1, 1);

	Liftaton(2000);

	driveaton(-100);

	pinchRRequestedValue = 1840;
	pinchLRequestedValue = 1805;

	wait1Msec(300);       //wait for previous command to finish

	Liftaton(1700);

	Liftaton(3500);

	driveaton(-200);

	driveaton(1000);

	pinchRRequestedValue = 350;
	pinchLRequestedValue = 210;

	wait1Msec(1000);       //wait for previous command to finish

	Liftaton(3000);
	setLiftPower(-15);


	driveaton(-1000);

	pinchRRequestedValue = 1840;
	pinchLRequestedValue = 1805;

	Liftaton(1570);

	Liftaton(3500);

	driveaton(1000);

	pinchRRequestedValue = 350;
	pinchLRequestedValue = 210;

	wait1Msec(300);       //wait for previous command to finish

	driveaton(-1000);

	dump();



}

//-------------------------------LEFT-------------------------//
task leftAton() {

	driveaton(-200);

	pinchRRequestedValue = 1840;
	pinchLRequestedValue = 1805;

	wait1Msec(10);       //wait for previous command to finish
	driveaton(-260);

	driveaton(80, 1, -1);

	wait1Msec(10);       //wait for previous command to finish
	driveaton(-250);

	wait1Msec(200);       //wait for previous command to finish
	Liftaton(1570);

	driveaton(-200);

	wait1Msec(300);       //wait for previous command to finish
	Liftaton(3600);								//------------------------------------------- End of jack command
	setLiftPower(15);

	driveaton(150);

	driveaton(190, -1, 1);

	driveaton(1500);

	pinchRRequestedValue = 350;
	pinchLRequestedValue = 210;

	wait1Msec(300);       //wait for previous command to finish

	Liftaton(3500);

	driveaton(200, 1, -1);

	wait1Msec(300);       //wait for previous command to finish

	driveaton(-600);

	Liftaton(3000);

	pinchRRequestedValue = 1840;
	pinchLRequestedValue = 1805;

	Liftaton(1600);

	Liftaton(3500);					//------------------------------------------- End of cube dump

	driveaton(-100);

	driveaton(20, 1, -1);

	driveaton(1000);

	pinchRRequestedValue = 350;
	pinchLRequestedValue = 210;

	wait1Msec(1000);       //wait for previous command to finish

	Liftaton(3500);

	driveaton(-1000);

	Liftaton(1570);

	pinchRRequestedValue = 1840;
	pinchLRequestedValue = 1805;

	wait1Msec(300);       //wait for previous command to finish

	Liftaton(3500);

}


/////////////////////////////////////////////////////////////////////////////////////////////////////////


void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	////setting initial value for the Arm and Pinch
	pinchRRequestedValue = SensorValue[ pinchR ];
	pinchLRequestedValue = SensorValue[ pinchL ];


	//// start the PID task's

	startTask( pinchRController );
	startTask( pinchLController );

	if (SensorValue[driveSelect] > 3900)
	{
		startTask(leftAton);

	}
	if (SensorValue[driveSelect] < 3900 && SensorValue[driveSelect] > 2080)
	{
		startTask(center);
	}

	if (SensorValue[driveSelect] < 2080 && SensorValue[driveSelect] > 450)
	{
		startTask(RightAton);
	}

	if (SensorValue[driveSelect] < 450)
	{
		startTask(skils);
	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	////setting initial value for the Arm and Pinch
	pinchRRequestedValue = SensorValue[ pinchR ];
	pinchLRequestedValue = SensorValue[ pinchL ];


	//// start the PID task's

	startTask( pinchRController );
	startTask( pinchLController );




	while (true)
	{
		///// drive control /////////////////////////////////////////////////////////////////

		setDrivePower(vexRT[Ch3], vexRT[Ch2]);




		///// lift control /////////////////////////////////////////////////////////////////
		int liftStillSpeedSet;

		if( vexRT[Btn5D] == 1 )
		{

			setLiftPower(127);

			liftStillSpeedSet=15;

		}

		else if( vexRT[Btn5U] == 1 )
		{

			setLiftPower(-127);

			liftStillSpeedSet=-15;
		}

		else
		{
			setLiftPower(liftStillSpeedSet);
			//	motor[Lift4] = liftStillSpeed Set;
			//	motor[Lift5] = liftStillSpeed Set;
		}



		//// pinch/claw control /////////////////////////////////////////////////////////////////////////////////

		if( vexRT[ Btn6U ] == 1 )
		{
			pinchRRequestedValue = 251;
			pinchLRequestedValue = 186;        ///Close claw
		}

		else if( vexRT[ Btn6D ] == 1)
		{
			pinchRRequestedValue = 1137;
			pinchLRequestedValue = 1137;         ///Open claw
		}

		else if(vexRT[Btn8U] == 1)
		{
			pinchRRequestedValue = 3620;
			pinchLRequestedValue = 3680;				// Reset Claw
		}

		else if(vexRT[Btn8L] == 1)
		{
			pinchRRequestedValue = 850;
			pinchLRequestedValue = 850;        //clamp 2 cubes
		}

		else if(vexRT[Btn8R] == 1)
		{
			pinchRRequestedValue = 1805;
			pinchLRequestedValue = 1805;     // Open for big loads
		}

		else if(vexRT[Btn8D] == 1)
		{
			dumpty();        //---auto dump

		}

		wait1Msec(50);

	}
}
