#pragma config(Sensor, in1,    MobileP,        sensorPotentiometer)
#pragma config(Sensor, in2,    selectPot,      sensorPotentiometer)
#pragma config(Sensor, in3,    Gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LexDrive,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RexDrive,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LDriveOne,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LDriveTwo,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RDriveOne,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RDriveTwo,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           RMobile,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LMobile,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"

#include "PIDS&Motors&Vars.c"
#include "AtonPrograms.c"
#include "Drive PID.c"
#include "AtonVoids.c"
//#region Drive Task
task drive() //Redirecting Drive into a task
{
	while (true)
	{
		setDrivePower(vexRT[Ch3], vexRT[Ch2]);
	}
wait1Msec(25);
}
//#endregion
//#region Pre-Autonomous Functions
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*---------------------------------------------------------------------------*/
void pre_auton()
{
}
//#endregion
//#region Autonomous Task
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task autonomous()
{

	//startTask(RPIDDriveController);
	//startTask(LPIDDriveController);
	startTask(TPIDDriveController);



	if (SensorValue[selectPot] < 2045)
	{
		Skills();
	}
	if (SensorValue[selectPot] > 2045)
	{
		TenPoint();
	}


}
//#endregion
//#region User Controll Task
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	startTask(drive);

  while (true)
  {
		  	//---------------------- Moblile Controll------------------------//
		if( vexRT[Btn6U] == 1)      // Setting Btn7U to Extend Goal
		{
			setMobilePower(-127);
			MobileStillSpeed=-15;

		}

		else if( vexRT[Btn6D] == 1)      // Setting Btn7D to Intake Goal
		{
			setMobilePower(127);
			MobileStillSpeed=15;

}

		else
		{setMobilePower(MobileStillSpeed);
		}

  }
}
//#endregion
