#pragma config(Sensor, in1,    liftP,          sensorPotentiometer)
#pragma config(Sensor, in2,    chainP,         sensorPotentiometer)
#pragma config(Sensor, in3,    selectP,        sensorPotentiometer)
#pragma config(Sensor, in4,    Gyro,           sensorGyro)
#pragma config(Sensor, in5,    mobileP,        sensorPotentiometer)
#pragma config(Sensor, in6,    selecttwoP,     sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           DriveR,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           chain,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           INtake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           liftL,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           liftR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           MobileR,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           MobileL,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RDrive,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LDrive,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          DriveL,        tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// This code is for the VEX cortex platform
#pragma platform(VEX2)
// Select Download method as "competition"
#pragma competitionControl(Competition)
//Main competition .background code...do not modify!
#include "Vex_Competition_Includes.c"
//include both Void programs, and PID
#include "BackOver Functions 2017-18.c"
#include "AutonTasks.c"
#include "Drive PID.c"

int liftstillspeed;      //define the liftstillspeed
int chainstillspeed;      //define the chainstillspeed
int mobilestillspeed;    //define the mobilegoalstillspeed
int skillsVar;           //skills toggle variable
int usertoggle;          //usertoggle variable
int initalize=0;         //initializeing the toggle variable
int curentteir = 1;
bool stackReadyAdd = true;
bool stackReadySubtract = true;

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*---------------------------------------------------------------------------*/
void pre_auton()
{
	SensorValue[rightEncoder] = 0;  ///
  SensorValue[leftEncoder] = 0;   ///  Making sure to clear all values
  bStopTasksBetweenModes = true;  ///
}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*---------------------------------------------------------------------------*/
task autonomous()
{
	startTask(liftRController);
	startTask(mobileRController);  //Start Mobile PID
	//startTask(LPIDDriveController);
	//startTask(RPIDDriveController);
	liftRSensorCurrentValue = SensorValue[ liftP ];
	//chainRRequestedValue = StraitUpChain;
/*
	SensorType[Gyro] = sensorNone;
	wait1Msec(500);
	SensorType[Gyro] = sensorGyro;
	SensorScale[Gyro] = 125;
	SensorFullCount[Gyro] = 3600;
	wait1Msec(2000);
*/
	if (SensorValue[selecttwoP] > 300 && SensorValue[selecttwoP] < 1795) //=========== Score 5's ==========//
	{
			if (SensorValue[selectP] == 0)
			{
				RightBlueFive();
			}
			if (SensorValue[selectP] > 1 && SensorValue[selectP] < 575)
			{
				LeftBlueFive();
			}
			if (SensorValue[selectP] > 575 && SensorValue[selectP] < 1185)
			{

			}
			if (SensorValue[selectP] > 1185 && SensorValue[selectP] < 1780)
			{

			}
			if (SensorValue[selectP] > 1780 && SensorValue[selectP] < 2410)
			{

			}
			if (SensorValue[selectP] > 2410 && SensorValue[selectP] < 3110)
			{

			}
			if (SensorValue[selectP] > 3110 && SensorValue[selectP] < 4094)
			{
				LeftRedFive();
			}
			if (SensorValue[selectP] == 4095)
			{
				RightRedFive();
			}

	}
	if (SensorValue[selecttwoP] > 1795 && SensorValue[selecttwoP] < 3530) //=========== Score 10's ==========//
	{
			if (SensorValue[selectP] == 0)
			{
				RightBlueTen();
			}
			if (SensorValue[selectP] > 1 && SensorValue[selectP] < 575)
			{
				LeftBlueTen();
			}
			if (SensorValue[selectP] > 575 && SensorValue[selectP] < 1185)
			{
				Defensive();
			}
			if (SensorValue[selectP] > 1185 && SensorValue[selectP] < 1780)
			{

			}
			if (SensorValue[selectP] > 1780 && SensorValue[selectP] < 2410)
			{

			}
			if (SensorValue[selectP] > 2410 && SensorValue[selectP] < 3110)
			{

			}
			if (SensorValue[selectP] > 3110 && SensorValue[selectP] < 4094)
			{
				LeftRedTen();
			}
			if (SensorValue[selectP] == 4095)
			{
				RightRedTen();
			}

	}
	if (SensorValue[selecttwoP] > 3530) //=========== Score 20's ==========//
	{
			if (SensorValue[selectP] == 0)
			{
				RightBlueTwenty();
			}
			if (SensorValue[selectP] > 1 && SensorValue[selectP] < 575)
			{
				LeftBlueTwenty();
			}
			if (SensorValue[selectP] > 575 && SensorValue[selectP] < 1185)
			{

			}
			if (SensorValue[selectP] > 1185 && SensorValue[selectP] < 1780)
			{

			}
			if (SensorValue[selectP] > 1780 && SensorValue[selectP] < 2410)
			{

			}
			if (SensorValue[selectP] > 2410 && SensorValue[selectP] < 3110)
			{

			}
			if (SensorValue[selectP] > 3110 && SensorValue[selectP] < 4094)
			{
				LeftRedTwenty();
			}
			if (SensorValue[selectP] == 4095)
			{
				RightRedTwenty();
			}

	}
	if (SensorValue[selecttwoP] < 300) //=========== Score Special's ==========//
	{
			if (SensorValue[selectP] == 0)
			{
				SkillsOne();
			}
			if (SensorValue[selectP] > 1 && SensorValue[selectP] < 575)
			{
				SkillsTwo();
			}
			if (SensorValue[selectP] > 575 && SensorValue[selectP] < 1185)
			{

			}
			if (SensorValue[selectP] > 1185 && SensorValue[selectP] < 1780)
			{

			}
			if (SensorValue[selectP] > 1780 && SensorValue[selectP] < 2410)
			{

			}
			if (SensorValue[selectP] > 2410 && SensorValue[selectP] < 3110)
			{

			}
			if (SensorValue[selectP] > 3110 && SensorValue[selectP] < 4094)
			{
				//LeftRedTwenty();
			}
			if (SensorValue[selectP] == 4095)
			{
				//RightRedTwenty();
			}

	}

}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*---------------------------------------------------------------------------*/
task usercontrol()
{
startTask(drive);

	while (3.1415926535897932384626433832795028841971==3.1415926535897932384626433832795028841971)
  //starting while loop to always run during userconroll
	{
		if (vexRT[Btn7L]==0)
		{
		usertoggle=1;
		}
		if (vexRT[Btn7L]==1 && skillsVar==1 && usertoggle==1)
		{
			skillsVar=0;
			usertoggle=0;
		}
		if (vexRT[Btn7L]==1 && skillsVar==0 && usertoggle==1)
		{
			skillsVar=1;
			usertoggle=0;
		}
	//=========================Normal Match Control===========================//
	if (skillsVar == 0)
	{
    if (initalize==0)
    {
      stopTask(liftRController);
    }
    initalize=1;

	//----------------------Lift Controll------------------------//

		if( vexRT[Btn5D] == 1)      // Setting Btn5D to lift Down
		{
			setLiftPower(-127);
			liftstillspeed=-15;
		}

		else if( vexRT[Btn5U] == 1)      // Setting Btn5U to lift Up
		{
			setLiftPower(127);
			liftstillspeed=15;
		}

		else if( vexRT[Btn5DXmtr2] == 1)      // Setting Btn5D to lift Down
		{
			setLiftPower(-127);
			liftstillspeed=-15;
		}

		else if( vexRT[Btn5UXmtr2] == 1)      // Setting Btn5U to lift Up
		{
			setLiftPower(127);
			liftstillspeed=15;
		}

		else
		{
			setLiftPower(liftstillspeed);
		}

	//----------------------Intake Control------------------------//

		if( vexRT[Btn6U] == 1)      // Setting Btn 6U to Intake Cone
		{
			startTask(IntakeCone);
		}

		else if( vexRT[Btn6D] == 1)      // Setting Btn6D to Outtake Cone
		{
			startTask(OutakeCone);
		}

		else if( vexRT[Btn8LXmtr2] == 1)      // Setting Btn 6U to Intake Cone
		{
			startTask(IntakeCone);
		}
		else if( vexRT[Btn8DXmtr2] == 1)      // Setting Btn6D to Outtake Cone
		{
			startTask(OutakeCone);
		}
	/*	else if (setIntakePower(Ch3Xmtr2)) {}// Setting Btn 6U to Intake Cone*/
/*
		else
		{
			setIntakePower(0);   // Else, set a intake still speed to hold cone in
		}*/

		//----------------------Moblie Goal Lift------------------------//
		if( vexRT[Btn7U] == 1)      // Setting Btn7U to Extend Goal
		{
				setMobilePower(127);
				mobilestillspeed=15;
		}

		else if( vexRT[Btn7D] == 1)      // Setting Btn7D to Intake Goal
		{
				setMobilePower(-127);
				mobilestillspeed=-15;
		}/*
		else if( vexRT[Btn6UXmtr2] == 1)      // Setting Btn 6U to Intake Cone
		{
			setMobilePower(-127);
		}
		else if( vexRT[Btn6DXmtr2] == 1)      // Setting Btn 6U to Intake Cone
		{
			setMobilePower(127);
		}
		else if( vexRT[Btn5UXmtr2] == 1)      // Setting Btn 6U to Intake Cone
		{
			setMobilePower(-64);
		}
		else if( vexRT[Btn5DXmtr2] == 1)      // Setting Btn 6U to Intake Cone
		{
			setMobilePower(64);
		}
*/
		else
		{
			setMobilePower(mobilestillspeed);      // Else, stop mobile motors
		}

		//----------------------Four Bar Control ------------------------//
		if( vexRT[Btn8D] == 1)
		{
			setChainPower(127);
			chainstillspeed=20;
		}

		else if( vexRT[Btn8R] == 1)
		{
			setChainPower(-127);
			chainstillspeed=-20;
		}
		else if( vexRT[Btn6DXmtr2] == 1)
		{
			setChainPower(127);
			chainstillspeed=20;
		}

		else if( vexRT[Btn6UXmtr2] == 1)
		{
			setChainPower(-127);
			chainstillspeed=-20;
		}

		else
		{
			setChainPower(chainstillspeed);
		}

//-=-=-=-==-=-=-=--=-=-Auto Stacking-=-=-=-=-=-=-=-=-=-=-=//

	if (vexRT[Btn7DXmtr2] == 1)
	{
		if(curentteir == 1)
		{
			startTask(liftRController);

					setIntakePower(127);
					wait1Msec(250);
					setIntakePower(10);
					wait1Msec(100);

					liftRRequestedValue = teirHeightOneTwo-300;
					wait1Msec(240);
					setChainPower(127);
					liftRRequestedValue = teirHeightOneTwo+200;
					wait1Msec(500);
					setChainPower(15);

					setIntakePower(-127);
					liftRRequestedValue = teirHeightOneTwo;
					wait1Msec(300);
					setIntakePower(-10);

					setChainPower(-127);
					wait1Msec(500);
					setChainPower(-10);

			stopTask(liftRController);
		}

		if(curentteir == 2)
		{
			startTask(liftRController);

					setIntakePower(127);
					wait1Msec(250);
					setIntakePower(10);
					wait1Msec(100);

					liftRRequestedValue = teirHeightOneTwo-300;
					wait1Msec(240);
					setChainPower(127);
					liftRRequestedValue = teirHeightOneTwo+200;
					wait1Msec(500);
					setChainPower(15);

					setIntakePower(-127);
					liftRRequestedValue = teirHeightOneTwo;
					wait1Msec(300);
					setIntakePower(-10);

					setChainPower(-127);
					wait1Msec(500);
					setChainPower(-10);

			stopTask(liftRController);
		}

		if(curentteir == 3)
		{
			startTask(liftRController);

					setIntakePower(127);
					wait1Msec(250);
					setIntakePower(10);
					wait1Msec(100);

					liftRRequestedValue = teirHeightThree-300;
					wait1Msec(240);
					setChainPower(127);
					liftRRequestedValue = teirHeightThree+200;
					wait1Msec(500);
					setChainPower(15);

					setIntakePower(-127);
					liftRRequestedValue = teirHeightThree;
					wait1Msec(300);
					setIntakePower(-10);

					setChainPower(-127);
					wait1Msec(500);
					setChainPower(-10);

			stopTask(liftRController);
		}

		if(curentteir == 4)
		{
			startTask(liftRController);

					setIntakePower(127);
					wait1Msec(250);
					setIntakePower(10);
					wait1Msec(100);

					liftRRequestedValue = teirHeightFour-300;
					wait1Msec(240);
					setChainPower(127);
					liftRRequestedValue = teirHeightFour+200;
					wait1Msec(500);
					setChainPower(15);

					setIntakePower(-127);
					liftRRequestedValue = teirHeightFour;
					wait1Msec(300);
					setIntakePower(-10);

					setChainPower(-127);
					wait1Msec(500);
					setChainPower(-10);

			stopTask(liftRController);
		}

		if(curentteir == 5)
		{
			startTask(liftRController);

					setIntakePower(127);
					wait1Msec(250);
					setIntakePower(10);
					wait1Msec(100);

					liftRRequestedValue = teirHeightFive-300;
					wait1Msec(240);
					setChainPower(127);
					liftRRequestedValue = teirHeightFive+300;
					wait1Msec(500);
					setChainPower(15);

					setIntakePower(-127);
					liftRRequestedValue = teirHeightFive;
					wait1Msec(300);
					setIntakePower(-10);

					setChainPower(-127);
					wait1Msec(500);
					setChainPower(-10);

			stopTask(liftRController);
		}

		if(curentteir == 6)
		{
			startTask(liftRController);

					setIntakePower(127);
					wait1Msec(250);
					setIntakePower(10);
					wait1Msec(100);

					liftRRequestedValue = teirHeightSix-300;
					wait1Msec(240);
					setChainPower(127);
					liftRRequestedValue = teirHeightSix+320;
					wait1Msec(500);
					setChainPower(15);

					setIntakePower(-127);
					liftRRequestedValue = teirHeightSix;
					wait1Msec(300);
					setIntakePower(-10);

					setChainPower(-127);
					wait1Msec(500);
					setChainPower(-10);

			stopTask(liftRController);
		}

		if(curentteir == 7)
		{
			startTask(liftRController);

					setIntakePower(127);
					wait1Msec(250);
					setIntakePower(10);
					wait1Msec(100);

					liftRRequestedValue = teirHeightSeven-300;
					wait1Msec(260);
					setChainPower(127);
					liftRRequestedValue = teirHeightSeven+250;
					wait1Msec(550);
					setChainPower(15);

					setIntakePower(-127);
					liftRRequestedValue = teirHeightSeven;
					wait1Msec(300);
					setIntakePower(-10);

					setChainPower(-127);
					wait1Msec(500);
					setChainPower(-10);

			stopTask(liftRController);
		}

		if(curentteir == 8)
		{
			startTask(liftRController);

					setIntakePower(127);
					wait1Msec(250);
					setIntakePower(10);
					wait1Msec(100);

					liftRRequestedValue = teirHeightEight-300;
					wait1Msec(260);
					setChainPower(127);
					liftRRequestedValue = teirHeightEight+350;
					wait1Msec(500);
					setChainPower(15);

					setIntakePower(-127);
					liftRRequestedValue = teirHeightEight;
					wait1Msec(300);
					setIntakePower(-10);

					setChainPower(-127);
					wait1Msec(500);
					setChainPower(-10);

			stopTask(liftRController);
		}

		if(curentteir == 9)
		{
			startTask(liftRController);

					setIntakePower(127);
					wait1Msec(250);
					setIntakePower(10);
					wait1Msec(100);

					liftRRequestedValue = teirHeightNine-310;
					wait1Msec(270);
					setChainPower(127);
					liftRRequestedValue = teirHeightNine+320;
					wait1Msec(500);
					setChainPower(15);

					setIntakePower(-127);
					liftRRequestedValue = teirHeightNine;
					wait1Msec(300);
					setIntakePower(-10);

					setChainPower(-127);
					wait1Msec(500);
					setChainPower(-10);

			stopTask(liftRController);
		}

		if(curentteir == 10)
		{
			startTask(liftRController);

					setIntakePower(127);
					wait1Msec(250);
					setIntakePower(10);
					wait1Msec(100);

					liftRRequestedValue = teirHeightTen-320;
					wait1Msec(300);
					setChainPower(127);
					liftRRequestedValue = teirHeightTen+340;
					wait1Msec(530);
					setChainPower(15);

					setIntakePower(-127);
					liftRRequestedValue = teirHeightTen;
					wait1Msec(300);
					setIntakePower(-10);

					setChainPower(-127);
					wait1Msec(500);
					setChainPower(-10);

			stopTask(liftRController);
		}

		if(curentteir == 11)
		{
			startTask(liftRController);

					setIntakePower(127);
					wait1Msec(250);
					setIntakePower(10);
					wait1Msec(100);

					liftRRequestedValue = teirHeightEleven-320;
					wait1Msec(310);
					setChainPower(127);
					liftRRequestedValue = teirHeightEleven+400;
					wait1Msec(560);
					setChainPower(15);

					setIntakePower(-127);
					liftRRequestedValue = teirHeightEleven;
					wait1Msec(300);
					setIntakePower(-10);

					setChainPower(-127);
					wait1Msec(500);
					setChainPower(-10);

			stopTask(liftRController);
		}

		if(curentteir == 12)
		{
			startTask(liftRController);

					setIntakePower(127);
					wait1Msec(250);
					setIntakePower(10);
					wait1Msec(100);

					liftRRequestedValue = teirHeightTwelve-300;
					wait1Msec(320);
					setChainPower(127);
					liftRRequestedValue = teirHeightTwelve+200;
					wait1Msec(500);
					setChainPower(15);

					setIntakePower(-127);
					liftRRequestedValue = teirHeightTwelve;
					wait1Msec(300);
					setIntakePower(-10);

					setChainPower(-127);
					wait1Msec(500);
					setChainPower(-10);

			stopTask(liftRController);
		}

		if(curentteir == 13)
		{
			startTask(liftRController);

					setIntakePower(127);
					wait1Msec(250);
					setIntakePower(10);
					wait1Msec(100);

					liftRRequestedValue = teirHeightThirteen-300;
					wait1Msec(330);
					setChainPower(127);
					liftRRequestedValue = teirHeightThirteen+200;
					wait1Msec(500);
					setChainPower(15);

					setIntakePower(-127);
					liftRRequestedValue = teirHeightThirteen;
					wait1Msec(300);
					setIntakePower(-10);

					setChainPower(-127);
					wait1Msec(500);
					setChainPower(-10);

			stopTask(liftRController);
		}

		if(curentteir == 14)
		{
			startTask(liftRController);

					setIntakePower(127);
					wait1Msec(250);
					setIntakePower(10);
					wait1Msec(100);

					liftRRequestedValue = teirHeightFourteen-300;
					wait1Msec(340);
					setChainPower(127);
					liftRRequestedValue = teirHeightFourteen+200;
					wait1Msec(500);
					setChainPower(15);

					setIntakePower(-127);
					liftRRequestedValue = teirHeightFourteen;
					wait1Msec(300);
					setIntakePower(-10);

					setChainPower(-127);
					wait1Msec(500);
					setChainPower(-10);

			stopTask(liftRController);
		}

		if(curentteir == 15)
		{
			startTask(liftRController);

					setIntakePower(127);
					wait1Msec(250);
					setIntakePower(10);
					wait1Msec(100);

					liftRRequestedValue = teirHeightFifteen-300;
					wait1Msec(350);
					setChainPower(127);
					liftRRequestedValue = teirHeightFifteen+200;
					wait1Msec(500);
					setChainPower(15);

					setIntakePower(-127);
					liftRRequestedValue = teirHeightFifteen;
					wait1Msec(300);
					setIntakePower(-10);

					setChainPower(-127);
					wait1Msec(500);
					setChainPower(-10);

			stopTask(liftRController);
		}
		curentteir++;
	}

	if (vexRT[Btn7LXmtr2] == 1 && stackReadyAdd == true)
	{
		curentteir++;
		stackReadyAdd = false;
	}
		else if (vexRT[Btn7LXmtr2] == 0)
	{
		stackReadyAdd = true;
	}
	if (vexRT[Btn7RXmtr2] == 1 && stackReadySubtract == true)
	{
		curentteir--;
		stackReadySubtract = false;
	}
		else if (vexRT[Btn7RXmtr2] == 0)
	{
		stackReadySubtract = true;
	}

	if (vexRT[Btn7UXmtr2] == 1)
	{
		curentteir = 1;
	}

}
//-=-=-=-==-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=//

//===========================================================================//

  if (skillsVar == 1)
  //--------------------------Specialties-Contol----------------------------//
  {
    if (initalize==1)
    {
      startTask(liftRController);
      liftRRequestedValue=SkillsLift;
      //chainRRequestedValue = StraitUpChain;
    }
    initalize=0;

    	setChainPower(20);

    //---------------------PreLoad Task-----------------------------//
    if (vexRT[Btn7R] == 1)
    {
    	//Preload();
    }
			//----------------------Moblie Goal Lift------------------------//
			if( vexRT[Btn6U] == 1)      // Setting Btn7U to Extend Goal
			{
				setMobilePower(127);
				mobilestillspeed=15;
			}

			else if( vexRT[Btn6D] == 1)      // Setting Btn7D to Intake Goal
			{
				setMobilePower(-127);
				mobilestillspeed=-15;
			}
			else
			{
				setMobilePower(mobilestillspeed);      // Else, stop mobile motors
			}

			//----------------------PIV Control with PID------------------------//
			if( vexRT[Btn8D] == 1)      // Setting Btn8D PID, to Strait Up
			{
				//chainRRequestedValue = StraitUpChain;
			}

			else if( vexRT[Btn8R] == 1)      // Setting Btn8R PID, to OutPosition
			{

				//chainRRequestedValue = OutPositionChain;
			}

			else if( vexRT[Btn8L] == 1)  // Setting Btn8L PID, to Stationary Position
			{
				//chainRRequestedValue = StationaryPositionChain;
			}
			else if( vexRT[Btn8U] == 1)      // Setting Btn8U PID, to In Position
			{
				//chainRRequestedValue = InPositionChain;
			}
    }
	}
}
